# Generated by Django 5.2.5 on 2025-09-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_invited_user_ids_event_is_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.RemoveField(
            model_name='memory',
            name='media_url',
        ),
        migrations.AddField(
            model_name='memory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memory',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='memories/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='liked_by_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='memory',
            name='year_created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', '-creation_date'], name='main_memory_user_id_6b505a_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['visibility', '-creation_date'], name='main_memory_visibil_5cd57d_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['location', '-creation_date'], name='main_memory_locatio_28f70f_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['is_featured', 'visibility'], name='main_memory_is_feat_48651e_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['media_type', 'visibility'], name='main_memory_media_t_e9c016_idx'),
        ),
    ]
